spring:
  mvc:
   view:
    prefix: /
    suffix: .jsp
  datasource: 
   driverClassName : com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/metaparkingspring
   username: root
   password: root